displayName=Restricted CA Tracker
author=crownpuff
description=Helps hide impossible CA for 1 defence and restricted accounts to get the missing green bar on their completed bosses!
tags=combat,achievements,restricted,ironman,hardcore, pure
plugins=com.restrictedcatracker.RestrictedCATrackerPlugin